#ifndef PN_CONST_VALUES_H
#define PN_CONST_VALUES_H

#include "string.hpp"

namespace Pubnub
{
    const Pubnub::String INTERNAL_MODERATION_PREFIX = "PUBNUB_INTERNAL_MODERATION_";
    const Pubnub::String INTERNAL_ADMIN_CHANNEL = "PUBNUB_INTERNAL_ADMIN_CHANNEL";
    const Pubnub::String MESSAGE_THREAD_ID_PREFIX = "PUBNUB_INTERNAL_THREAD";
    const Pubnub::String ERROR_LOGGER_KEY_PREFIX = "PUBNUB_INTERNAL_ERROR_LOGGER";
}
#endif /* PN_CONST_VALUES_H */
